//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.03 at 04:39:08 PM BST 
//
package uk.ac.core.rioxxvalidation.rioxx.jaxb_v2.jaxb;

import uk.ac.core.rioxxvalidation.rioxx.jaxb_v2.RioxxCompliance;
import uk.ac.core.rioxxvalidation.rioxx.jaxb_v2.jaxb.net.rioxx.schema.v2_0.rioxxterms.ApcList;
import uk.ac.core.rioxxvalidation.rioxx.jaxb_v2.jaxb.net.rioxx.schema.v2_0.rioxxterms.Author;
import uk.ac.core.rioxxvalidation.rioxx.jaxb_v2.jaxb.net.rioxx.schema.v2_0.rioxxterms.Contributor;
import uk.ac.core.rioxxvalidation.rioxx.jaxb_v2.jaxb.net.rioxx.schema.v2_0.rioxxterms.Project;
import uk.ac.core.rioxxvalidation.rioxx.jaxb_v2.jaxb.net.rioxx.schema.v2_0.rioxxterms.TypeList;
import uk.ac.core.rioxxvalidation.rioxx.jaxb_v2.jaxb.net.rioxx.schema.v2_0.rioxxterms.VersionList;
import uk.ac.core.rioxxvalidation.rioxx.jaxb_v2.jaxb.org.niso.ali._2014.ali._1.FreeToRead;
import uk.ac.core.rioxxvalidation.rioxx.jaxb_v2.jaxb.org.niso.ali._2014.ali._1.LicenseRef;
import uk.ac.core.rioxxvalidation.rioxx.jaxb_v3.entity.dc.elements._1.SimpleLiteral;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import java.util.List;

/**
 * <p>
 * Java class for anonymous complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{http://www.rioxx.net/schema/v2.0/rioxxterms/}apc" minOccurs="0"/>
 *         &lt;element ref="{http://www.rioxx.net/schema/v2.0/rioxxterms/}author"/>
 *         &lt;element ref="{http://www.rioxx.net/schema/v2.0/rioxxterms/}contributor" minOccurs="0"/>
 *         &lt;element ref="{http://purl.org/dc/elements/1.1/}coverage" minOccurs="0"/>
 *         &lt;element ref="{http://purl.org/dc/terms/}dateAccepted"/>
 *         &lt;element ref="{http://purl.org/dc/elements/1.1/}description" minOccurs="0"/>
 *         &lt;element ref="{http://ali.niso.org/2014/ali/1.0}free_to_read" minOccurs="0"/>
 *         &lt;element ref="{http://purl.org/dc/elements/1.1/}format" minOccurs="0"/>
 *         &lt;element ref="{http://purl.org/dc/elements/1.1/}identifier"/>
 *         &lt;element ref="{http://purl.org/dc/elements/1.1/}language"/>
 *         &lt;element ref="{http://ali.niso.org/2014/ali/1.0}license_ref"/>
 *         &lt;element ref="{http://www.rioxx.net/schema/v2.0/rioxxterms/}project"/>
 *         &lt;element ref="{http://www.rioxx.net/schema/v2.0/rioxxterms/}publication_date" minOccurs="0"/>
 *         &lt;element ref="{http://purl.org/dc/elements/1.1/}publisher" minOccurs="0"/>
 *         &lt;element ref="{http://purl.org/dc/elements/1.1/}relation" minOccurs="0"/>
 *         &lt;element ref="{http://purl.org/dc/elements/1.1/}source" minOccurs="0"/>
 *         &lt;element ref="{http://purl.org/dc/elements/1.1/}subject" minOccurs="0"/>
 *         &lt;element ref="{http://purl.org/dc/elements/1.1/}title"/>
 *         &lt;element ref="{http://www.rioxx.net/schema/v2.0/rioxxterms/}type"/>
 *         &lt;element ref="{http://www.rioxx.net/schema/v2.0/rioxxterms/}version"/>
 *         &lt;element ref="{http://www.rioxx.net/schema/v2.0/rioxxterms/}version-of-record" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {})
@XmlRootElement(name = "rioxx")
public class Rioxx {

    @XmlElement(namespace = "http://www.rioxx.net/schema/v2.0/rioxxterms/", defaultValue = "unknown")
    @RioxxCompliance(basicMinOccur = "0", fullMinOccur = "0")
    protected ApcList apc;
    @XmlElement(namespace = "http://www.rioxx.net/schema/v2.0/rioxxterms/", required = true)
    @RioxxCompliance(basicMinOccur = "1", fullMinOccur = "1")
    protected List<Author> author;
    @XmlElement(namespace = "http://www.rioxx.net/schema/v2.0/rioxxterms/")
    @RioxxCompliance(basicMinOccur = "0", fullMinOccur = "0")
    protected List<Contributor> contributor;
    @XmlElementRef(name = "coverage", namespace = "http://purl.org/dc/elements/1.1/", type = JAXBElement.class, required = false)
    @RioxxCompliance(basicMinOccur = "0", fullMinOccur = "0")
    protected List<JAXBElement<SimpleLiteral>> coverage;
    @XmlElement(namespace = "http://purl.org/dc/terms/", required = true)
    @RioxxCompliance(basicMinOccur = "0", fullMinOccur = "1")
    protected SimpleLiteral dateAccepted;
    @XmlElementRef(name = "description", namespace = "http://purl.org/dc/elements/1.1/", type = JAXBElement.class, required = false)
    @RioxxCompliance(basicMinOccur = "0", fullMinOccur = "0")
    protected List<JAXBElement<SimpleLiteral>> description;
    @XmlElement(name = "free_to_read", namespace = "http://ali.niso.org/2014/ali/1.0")
    @RioxxCompliance(basicMinOccur = "0", fullMinOccur = "0")
    protected FreeToRead freeToRead;
    @XmlElementRef(name = "format", namespace = "http://purl.org/dc/elements/1.1/", type = JAXBElement.class, required = false)
    @RioxxCompliance(basicMinOccur = "0", fullMinOccur = "0")
    protected List<JAXBElement<SimpleLiteral>> format;
    @XmlElementRef(name = "identifier", namespace = "http://purl.org/dc/elements/1.1/", type = JAXBElement.class)
    @RioxxCompliance(basicMinOccur = "1", fullMinOccur = "1")
    protected JAXBElement<SimpleLiteral> identifier;
    @XmlElementRef(name = "language", namespace = "http://purl.org/dc/elements/1.1/", type = JAXBElement.class)
    @RioxxCompliance(basicMinOccur = "0", fullMinOccur = "1")
    protected List<JAXBElement<SimpleLiteral>> language;
    @XmlElement(name = "license_ref", namespace = "http://ali.niso.org/2014/ali/1.0", required = true)
    @RioxxCompliance(basicMinOccur = "0", fullMinOccur = "1")
    protected List<LicenseRef> licenseRef;
    @XmlElement(namespace = "http://www.rioxx.net/schema/v2.0/rioxxterms/", required = true)
    @RioxxCompliance(basicMinOccur = "0", fullMinOccur = "1")
    protected List<Project> project;
    @XmlElement(name = "publication_date", namespace = "http://www.rioxx.net/schema/v2.0/rioxxterms/")
    @RioxxCompliance(basicMinOccur = "0", fullMinOccur = "0")
    protected Object publicationDate;
    @XmlElementRef(name = "publisher", namespace = "http://purl.org/dc/elements/1.1/", type = JAXBElement.class, required = false)
    @RioxxCompliance(basicMinOccur = "0", fullMinOccur = "0")
    protected List<JAXBElement<SimpleLiteral>> publisher;
    @XmlElementRef(name = "relation", namespace = "http://purl.org/dc/elements/1.1/", type = JAXBElement.class, required = false)
    @RioxxCompliance(basicMinOccur = "0", fullMinOccur = "0")
    protected List<JAXBElement<SimpleLiteral>> relation;
    @XmlElementRef(name = "source", namespace = "http://purl.org/dc/elements/1.1/", type = JAXBElement.class, required = false)
    @RioxxCompliance(basicMinOccur = "0", fullMinOccur = "0")
    protected JAXBElement<SimpleLiteral> source;
    @XmlElementRef(name = "subject", namespace = "http://purl.org/dc/elements/1.1/", type = JAXBElement.class, required = false)
    @RioxxCompliance(basicMinOccur = "0", fullMinOccur = "0")
    protected List<JAXBElement<SimpleLiteral>> subject;
    @XmlElementRef(name = "title", namespace = "http://purl.org/dc/elements/1.1/", type = JAXBElement.class)
    @RioxxCompliance(basicMinOccur = "1", fullMinOccur = "1")
    protected JAXBElement<SimpleLiteral> title;
    @XmlElement(namespace = "http://www.rioxx.net/schema/v2.0/rioxxterms/", required = true)
    @RioxxCompliance(basicMinOccur = "0", fullMinOccur = "1")
    protected List<TypeList> type;
    @XmlElement(namespace = "http://www.rioxx.net/schema/v2.0/rioxxterms/", required = true)
    @RioxxCompliance(basicMinOccur = "0", fullMinOccur = "1")
    protected VersionList version;
    @XmlElement(name = "version-of-record", namespace = "http://www.rioxx.net/schema/v2.0/rioxxterms/")
    @RioxxCompliance(basicMinOccur = "0", fullMinOccur = "0")
    @XmlSchemaType(name = "anyURI")
    protected String versionOfRecord;

    public ApcList getApc() {
        return apc;
    }

    public void setApc(ApcList apc) {
        this.apc = apc;
    }

    public List<Author> getAuthor() {
        return author;
    }

    public void setAuthor(List<Author> author) {
        this.author = author;
    }

    public List<Contributor> getContributor() {
        return contributor;
    }

    public void setContributor(List<Contributor> contributor) {
        this.contributor = contributor;
    }

    public List<JAXBElement<SimpleLiteral>> getCoverage() {
        return coverage;
    }

    public void setCoverage(List<JAXBElement<SimpleLiteral>> coverage) {
        this.coverage = coverage;
    }

    public SimpleLiteral getDateAccepted() {
        return dateAccepted;
    }

    public void setDateAccepted(SimpleLiteral dateAccepted) {
        this.dateAccepted = dateAccepted;
    }

    public List<JAXBElement<SimpleLiteral>> getDescription() {
        return description;
    }

    public void setDescription(List<JAXBElement<SimpleLiteral>> description) {
        this.description = description;
    }

    public FreeToRead getFreeToRead() {
        return freeToRead;
    }

    public void setFreeToRead(FreeToRead freeToRead) {
        this.freeToRead = freeToRead;
    }

    public List<JAXBElement<SimpleLiteral>> getFormat() {
        return format;
    }

    public void setFormat(List<JAXBElement<SimpleLiteral>> format) {
        this.format = format;
    }

    public JAXBElement<SimpleLiteral> getIdentifier() {
        return identifier;
    }

    public void setIdentifier(JAXBElement<SimpleLiteral> identifier) {
        this.identifier = identifier;
    }

    public List<JAXBElement<SimpleLiteral>> getLanguage() {
        return language;
    }

    public void setLanguage(List<JAXBElement<SimpleLiteral>> language) {
        this.language = language;
    }

    public List<LicenseRef> getLicenseRef() {
        return licenseRef;
    }

    public void setLicenseRef(List<LicenseRef> licenseRef) {
        this.licenseRef = licenseRef;
    }

    public List<Project> getProject() {
        return project;
    }

    public void setProject(List<Project> project) {
        this.project = project;
    }

    public Object getPublicationDate() {
        return publicationDate;
    }

    public void setPublicationDate(Object publicationDate) {
        this.publicationDate = publicationDate;
    }

    public List<JAXBElement<SimpleLiteral>> getPublisher() {
        return publisher;
    }

    public void setPublisher(List<JAXBElement<SimpleLiteral>> publisher) {
        this.publisher = publisher;
    }

    public List<JAXBElement<SimpleLiteral>> getRelation() {
        return relation;
    }

    public void setRelation(List<JAXBElement<SimpleLiteral>> relation) {
        this.relation = relation;
    }

    public JAXBElement<SimpleLiteral> getSource() {
        return source;
    }

    public void setSource(JAXBElement<SimpleLiteral> source) {
        this.source = source;
    }

    public List<JAXBElement<SimpleLiteral>> getSubject() {
        return subject;
    }

    public void setSubject(List<JAXBElement<SimpleLiteral>> subject) {
        this.subject = subject;
    }

    public JAXBElement<SimpleLiteral> getTitle() {
        return title;
    }

    public void setTitle(JAXBElement<SimpleLiteral> title) {
        this.title = title;
    }

    public List<TypeList> getType() {
        return type;
    }

    public void setType(List<TypeList> type) {
        this.type = type;
    }

    public VersionList getVersion() {
        return version;
    }

    public void setVersion(VersionList version) {
        this.version = version;
    }

    public String getVersionOfRecord() {
        return versionOfRecord;
    }

    public void setVersionOfRecord(String versionOfRecord) {
        this.versionOfRecord = versionOfRecord;
    }

}
