//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.03 at 04:39:08 PM BST 
//


package uk.ac.core.rioxxvalidation.rioxx.jaxb_v3.entity.dc.elements._1;

import uk.ac.core.rioxxvalidation.rioxx.jaxb_v3.entity.dc.terms.Box;
import uk.ac.core.rioxxvalidation.rioxx.jaxb_v3.entity.dc.terms.DCMIType;
import uk.ac.core.rioxxvalidation.rioxx.jaxb_v3.entity.dc.terms.DDC;
import uk.ac.core.rioxxvalidation.rioxx.jaxb_v3.entity.dc.terms.IMT;
import uk.ac.core.rioxxvalidation.rioxx.jaxb_v3.entity.dc.terms.ISO3166;
import uk.ac.core.rioxxvalidation.rioxx.jaxb_v3.entity.dc.terms.ISO6392;
import uk.ac.core.rioxxvalidation.rioxx.jaxb_v3.entity.dc.terms.ISO6393;
import uk.ac.core.rioxxvalidation.rioxx.jaxb_v3.entity.dc.terms.LCC;
import uk.ac.core.rioxxvalidation.rioxx.jaxb_v3.entity.dc.terms.LCSH;
import uk.ac.core.rioxxvalidation.rioxx.jaxb_v3.entity.dc.terms.MESH;
import uk.ac.core.rioxxvalidation.rioxx.jaxb_v3.entity.dc.terms.Period;
import uk.ac.core.rioxxvalidation.rioxx.jaxb_v3.entity.dc.terms.Point;
import uk.ac.core.rioxxvalidation.rioxx.jaxb_v3.entity.dc.terms.RFC1766;
import uk.ac.core.rioxxvalidation.rioxx.jaxb_v3.entity.dc.terms.RFC3066;
import uk.ac.core.rioxxvalidation.rioxx.jaxb_v3.entity.dc.terms.RFC4646;
import uk.ac.core.rioxxvalidation.rioxx.jaxb_v3.entity.dc.terms.TGN;
import uk.ac.core.rioxxvalidation.rioxx.jaxb_v3.entity.dc.terms.UDC;
import uk.ac.core.rioxxvalidation.rioxx.jaxb_v3.entity.dc.terms.URI;
import uk.ac.core.rioxxvalidation.rioxx.jaxb_v3.entity.dc.terms.W3CDTF;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * 
 *             This is the default type for all of the DC elements.
 *             It permits text content only with optional
 *             xml:lang attribute.
 *             Text is allowed because mixed="true", but sub-elements
 *             are disallowed because minOccurs="0" and maxOccurs="0" 
 *             are on the xs:any tag.
 * 
 *     	    This complexType allows for restriction or extension permitting
 *             child elements.
 *     	
 * 
 * <p>Java class for SimpleLiteral complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SimpleLiteral">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;any processContents='lax' maxOccurs="0" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute ref="{http://www.w3.org/XML/1998/namespace}lang"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SimpleLiteral", propOrder = {
    "content"
})
@XmlSeeAlso({
    DDC.class,
    ISO6392.class,
    ISO6393.class,
    MESH.class,
    Period.class,
    RFC4646.class,
    Box.class,
    Point.class,
    W3CDTF.class,
    RFC1766.class,
    LCC.class,
    URI.class,
    LCSH.class,
    IMT.class,
    UDC.class,
    DCMIType.class,
    RFC3066.class,
    ISO3166.class,
    TGN.class
})
public class SimpleLiteral {

    @XmlMixed
    protected List<String> content;
    @XmlAttribute(name = "lang", namespace = "http://www.w3.org/XML/1998/namespace")
    protected String lang;

    /**
     * 
     *             This is the default type for all of the DC elements.
     *             It permits text content only with optional
     *             xml:lang attribute.
     *             Text is allowed because mixed="true", but sub-elements
     *             are disallowed because minOccurs="0" and maxOccurs="0" 
     *             are on the xs:any tag.
     * 
     *     	    This complexType allows for restriction or extension permitting
     *             child elements.
     *     	Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getContent() {
        if (content == null) {
            content = new ArrayList<String>();
        }
        return this.content;
    }

    /**
     * Gets the value of the lang property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLang() {
        return lang;
    }

    /**
     * Sets the value of the lang property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLang(String value) {
        this.lang = value;
    }

}
