//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.03 at 04:39:08 PM BST 
//


package uk.ac.core.rioxxvalidation.rioxx.jaxb_v2.jaxb.net.rioxx.schema.v2_0.rioxxterms;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for apcList.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="apcList">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="paid"/>
 *     &lt;enumeration value="partially waived"/>
 *     &lt;enumeration value="fully waived"/>
 *     &lt;enumeration value="not charged"/>
 *     &lt;enumeration value="not required"/>
 *     &lt;enumeration value="unknown"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "apcList")
@XmlEnum
public enum ApcList {

    @XmlEnumValue("paid")
    PAID("paid"),
    @XmlEnumValue("partially waived")
    PARTIALLY_WAIVED("partially waived"),
    @XmlEnumValue("fully waived")
    FULLY_WAIVED("fully waived"),
    @XmlEnumValue("not charged")
    NOT_CHARGED("not charged"),
    @XmlEnumValue("not required")
    NOT_REQUIRED("not required"),
    @XmlEnumValue("unknown")
    UNKNOWN("unknown");
    private final String value;

    ApcList(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ApcList fromValue(String v) {
        for (ApcList c: ApcList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
