//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.03 at 04:39:08 PM BST 
//


package uk.ac.core.rioxxvalidation.rioxx.jaxb_v2.jaxb.net.rioxx.schema.v2_0.rioxxterms;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the net.rioxx.schema.v2_0.rioxxterms package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _PublicationDate_QNAME = new QName("http://www.rioxx.net/schema/v2.0/rioxxterms/", "publication_date");
    private final static QName _Type_QNAME = new QName("http://www.rioxx.net/schema/v2.0/rioxxterms/", "type");
    private final static QName _VersionOfRecord_QNAME = new QName("http://www.rioxx.net/schema/v2.0/rioxxterms/", "version-of-record");
    private final static QName _Apc_QNAME = new QName("http://www.rioxx.net/schema/v2.0/rioxxterms/", "apc");
    private final static QName _Version_QNAME = new QName("http://www.rioxx.net/schema/v2.0/rioxxterms/", "version");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: net.rioxx.schema.v2_0.rioxxterms
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Author }
     * 
     */
    public Author createAuthor() {
        return new Author();
    }

    /**
     * Create an instance of {@link Contributor }
     * 
     */
    public Contributor createContributor() {
        return new Contributor();
    }

    /**
     * Create an instance of {@link Project }
     * 
     */
    public Project createProject() {
        return new Project();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.rioxx.net/schema/v2.0/rioxxterms/", name = "publication_date")
    public JAXBElement<Object> createPublicationDate(Object value) {
        return new JAXBElement<Object>(_PublicationDate_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypeList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.rioxx.net/schema/v2.0/rioxxterms/", name = "type")
    public JAXBElement<TypeList> createType(TypeList value) {
        return new JAXBElement<TypeList>(_Type_QNAME, TypeList.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.rioxx.net/schema/v2.0/rioxxterms/", name = "version-of-record")
    public JAXBElement<String> createVersionOfRecord(String value) {
        return new JAXBElement<String>(_VersionOfRecord_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ApcList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.rioxx.net/schema/v2.0/rioxxterms/", name = "apc", defaultValue = "unknown")
    public JAXBElement<ApcList> createApc(ApcList value) {
        return new JAXBElement<ApcList>(_Apc_QNAME, ApcList.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VersionList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.rioxx.net/schema/v2.0/rioxxterms/", name = "version")
    public JAXBElement<VersionList> createVersion(VersionList value) {
        return new JAXBElement<VersionList>(_Version_QNAME, VersionList.class, null, value);
    }

}
