//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.03 at 04:39:08 PM BST 
//


package uk.ac.core.rioxxvalidation.rioxx.jaxb_v2.jaxb.net.rioxx.schema.v2_0.rioxxterms;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute ref="{http://www.rioxx.net/schema/v2.0/rioxxterms/}funder_name"/>
 *       &lt;attribute ref="{http://www.rioxx.net/schema/v2.0/rioxxterms/}funder_id"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "content"
})
@XmlRootElement(name = "project")
public class Project {

    @XmlValue
    protected String content;
    @XmlAttribute(name = "funder_name", namespace = "http://www.rioxx.net/schema/v2.0/rioxxterms/")
    @XmlSchemaType(name = "anySimpleType")
    protected String funderName;
    @XmlAttribute(name = "funder_id", namespace = "http://www.rioxx.net/schema/v2.0/rioxxterms/")
    @XmlSchemaType(name = "anyURI")
    protected String funderId;

    /**
     * Gets the value of the content property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContent() {
        return content;
    }

    /**
     * Sets the value of the content property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContent(String value) {
        this.content = value;
    }

    /**
     * Gets the value of the funderName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFunderName() {
        return funderName;
    }

    /**
     * Sets the value of the funderName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFunderName(String value) {
        this.funderName = value;
    }

    /**
     * Gets the value of the funderId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFunderId() {
        return funderId;
    }

    /**
     * Sets the value of the funderId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFunderId(String value) {
        this.funderId = value;
    }

}
